### ISSUE TITLE
Certificate Signature Verification failed because the signature is invalid.

### ISSUE THREAD

**Issue by bytesofdhiren** [grinich/mdmvendorsign#6]
I am trying to upload the plist file to apple but getting the error as Certificate Signature Verification failed because the signature is invalid.

I have performed following steps locally
1. openssl genrsa -des3 -out customerPrivateKey.pem 2048
2. openssl req -new -key customerPrivateKey.pem -out customer.csr
3. Uploaded customer.csr to apple enterprise account certificate and downloaded mdm.cer file. 

Now I am running the script to generate plist file. It's sucessfuly generating the file but when I upload the file to server I recieve the error as "Certificate Signature Verification failed because the signature is invalid."

**Comment by dhirenrouterabbit** [comment]
I read your earlier issue https://github.com/grinich/mdmvendorsign/issues/1#issuecomment-22968436 but in my case I am the vendor. I am creating MDM server.

**Comment by Zeo22** [comment]
This is issue is old, but now, if you are having problems with the Signature Verification, its probably because the certificate Apple WWDR CA expiration, I had to add the latest AppleWWDRCAG3 certificate to the certificate chain on the plist needed for APNS renew.
This might clear things a bit for you https://developer.apple.com/support/expiration/
 "The renewed certificate will be used to sign new software signing certificates issued after January 28, 2021"

**Comment by ezzzzd5** [comment]
@Zeo22 It's solved. Thank you very much
